[build-system]
name = "ebook2audiobook"
version = "25.2.0"
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "ebook2audiobook"
version = "25.2.0"
description = "Convert Ebook to Audiobook with chapters and metadata"
authors = [
    { name = "Drew Thomasson" }
]
dependencies = [
    "beautifulsoup4",
    "cutlet",
    "deep_translator",
    "demucs",
    "docker",
    "ebooklib",
    "fastapi",
    "ffmpeg-python",
    "gensim",
    "gradio",
    "hangul-romanize",
    "indic-nlp-library",
    "iso-639",
    "jieba",
    "m4b-util",
    "mecab",
    "mecab-python3",
    "pydub",
    "pypinyin",
    "ray",
    "regex",
    "sentencepiece",
    "torchvggish",
    "transformers",
    "translate",
    "tqdm",
    "unidic",
    "coqui-tts==0.25.3"
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
scripts = { "ebook2audiobook" = "app:main" }

[project.urls]
"Homepage" = "https://github.com/DrewThomasson/ebook2audiobook"
