name: Run Ubuntu Headless ebook2audiobook 

on:
  workflow_dispatch:


jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Check Python version
        run: python --version
        
      - name: Install the system packages
        run: |
          sudo apt-get update &&
          sudo apt-get install -y wget git calibre ffmpeg nodejs espeak espeak-ng rustc cargo libmecab-dev mecab mecab-ipadic-utf8 curl &&
          sudo apt-get clean &&
          sudo rm -rf /var/lib/apt/lists/*
      - name: Install the python requirements
        run: |
          python -m pip install --upgrade pip
          pip cache purge
          pip install -r requirements.txt

      - name: pip Install unict
        run: pip install unidic

      - name: Download the unict dictionary
        run: python -m unidic download

      - name: Help command python app.py
        run: python app.py --help

      - name: Create test files
        run: |
          mkdir workflow-testing
          echo "This is test sentence 1 ." > workflow-testing/test1.txt
          echo "This is test sentence 2 ." > workflow-testing/test2.txt
          echo "This is test sentence 3 ." > workflow-testing/test3.txt
          echo "This is test sentence 4 ." > workflow-testing/test4.txt
          echo "This is test sentence 5 ." > workflow-testing/test5.txt

      - name: Default headless single test python app.py
        run: python app.py --headless --ebook "workflow-testing/test1.txt"

      - name: Default xtts headless batch test python app.py
        run: python app.py --headless --ebooks_dir "workflow-testing" --tts_engine xtts

      - name: Default xtts headless Custom-Voice single test python app.py
        run: python app.py --headless --ebook "workflow-testing/test1.txt" --tts_engine xtts --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      - name: Default xtts headless Custom-Voice batch test python app.py
        run: python app.py --headless --ebooks_dir "workflow-testing" --tts_engine xtts --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      - name: Create the custom_xtts_test.zip for headless custom xtts model single test python app.py
        run: cp voices/eng/elder/male/DavidAttenborough_24000.wav ref.wav && zip -j custom_xtts_test.zip models/tts/tts_models--multilingual--multi-dataset--xtts_v2/config.json models/tts/tts_models--multilingual--multi-dataset--xtts_v2/model.pth models/tts/tts_models--multilingual--multi-dataset--xtts_v2/vocab.json ref.wav && rm ref.wav

      - name: English xtts headless custom xtts model single test python app.py
        run: python app.py --headless --language eng --ebook "workflow-testing/test1.txt" --tts_engine xtts --custom_model "custom_xtts_test.zip"

      - name: English xtts headless custom xtts model batch test python app.py
        run: python app.py --headless --language eng --ebooks_dir "workflow-testing" --tts_engine xtts --custom_model "custom_xtts_test.zip"

      - name: English Fairseq headless single test python app.py
        run: python app.py --headless --language eng --ebook "workflow-testing/test1.txt" --tts_engine fairseq

      - name: English Fairseq headless batch test python app.py
        run: python app.py --headless --language eng --ebooks_dir "workflow-testing" --tts_engine fairseq

      - name: English Fairseq Custom-Voice headless single test python app.py
        run: python app.py --headless --language eng --ebook "workflow-testing/test1.txt" --tts_engine fairseq --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      - name: English Fairseq Custom-Voice headless batch test python app.py
        run: python app.py --headless --language eng --ebooks_dir "workflow-testing" --tts_engine fairseq --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      - name: Unusual Fairseq headless single test python app.py
        run: python app.py --headless --language urd-script_devanagari --ebook "workflow-testing/test1.txt" --tts_engine fairseq

      - name: Unusual Fairseq headless batch test python app.py
        run: python app.py --headless --language urd-script_devanagari --ebooks_dir "workflow-testing" --tts_engine fairseq

      - name: Unusual Fairseq Custom-Voice headless single test python app.py
        run: python app.py --headless --language urd-script_devanagari --ebook "workflow-testing/test1.txt" --tts_engine fairseq --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      - name: Unusual Fairseq  Custom-Voice headless batch test python app.py
        run: python app.py --headless --language urd-script_devanagari --ebooks_dir "workflow-testing" --tts_engine fairseq --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"
